name: Continuous Integration
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  automation-test-job:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean previous dependencies
        run: |
          rm -rf node_modules package-lock.json
      - name: npm install and test
        run: |
          npm install --no-optional
          npm run ci:test
